token = "MTM4MjMyNjg3MzM2NjcyODc0NA.GvwT65.qCbqBIypiFjV2a9CMS0ycXc_3B-WpTRhhaLeTo"
prefix = "!"

[music]
max_volume = 250
vote_skip = true
vote_skip_ratio = 0.5

[tips]
github_url = "https://github.com/joek13/py-music-bot"
